# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bad_guy_last_key_press',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_guy_position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_guy_position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_guy_position_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_guy_rotation_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_guy_rotation_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_guy_rotation_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_last_key_press',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_position_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_rotation_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_rotation_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_guy_rotation_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
