# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0005_auto_20161226_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bad_ship_position_x',
            field=models.FloatField(default=40.3),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_ship_position_y',
            field=models.FloatField(default=5.9),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_ship_position_z',
            field=models.FloatField(default=-2),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_ship_rotation_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_ship_rotation_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bad_ship_rotation_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_ship_position_x',
            field=models.FloatField(default=-22.09),
        ),
        migrations.AddField(
            model_name='game',
            name='good_ship_position_y',
            field=models.FloatField(default=5.33),
        ),
        migrations.AddField(
            model_name='game',
            name='good_ship_position_z',
            field=models.FloatField(default=-0.15),
        ),
        migrations.AddField(
            model_name='game',
            name='good_ship_rotation_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_ship_rotation_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='good_ship_rotation_z',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='bad_guy_position_x',
            field=models.FloatField(default=-2.2453),
        ),
        migrations.AlterField(
            model_name='game',
            name='bad_guy_position_y',
            field=models.FloatField(default=2.51678),
        ),
        migrations.AlterField(
            model_name='game',
            name='bad_guy_position_z',
            field=models.FloatField(default=0.7289),
        ),
        migrations.AlterField(
            model_name='game',
            name='good_guy_position_x',
            field=models.FloatField(default=-2.3973),
        ),
        migrations.AlterField(
            model_name='game',
            name='good_guy_position_y',
            field=models.FloatField(default=2.82932),
        ),
        migrations.AlterField(
            model_name='game',
            name='good_guy_position_z',
            field=models.FloatField(default=-0.1822),
        ),
    ]
