# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0006_auto_20161226_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bad_guy_position_x',
            field=models.FloatField(default=35.87),
        ),
        migrations.AlterField(
            model_name='game',
            name='bad_guy_position_y',
            field=models.FloatField(default=10.49),
        ),
        migrations.AlterField(
            model_name='game',
            name='bad_guy_position_z',
            field=models.FloatField(default=-0.52),
        ),
        migrations.AlterField(
            model_name='game',
            name='good_guy_position_x',
            field=models.FloatField(default=-26.82),
        ),
        migrations.AlterField(
            model_name='game',
            name='good_guy_position_y',
            field=models.FloatField(default=10.49),
        ),
        migrations.AlterField(
            model_name='game',
            name='good_guy_position_z',
            field=models.FloatField(default=-0.52),
        ),
    ]
