# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0007_auto_20161227_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location_x', models.FloatField()),
                ('start_location_y', models.FloatField()),
                ('start_location_z', models.FloatField()),
                ('firing_force_x', models.FloatField()),
                ('firing_force_y', models.FloatField()),
                ('firing_force_z', models.FloatField()),
                ('rendered_in_enemy_client', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='projectiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_blimp.Projectile'),
        ),
    ]
