# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0008_auto_20161227_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='projectiles',
        ),
        migrations.AddField(
            model_name='projectile',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectiles', to='api_blimp.Game'),
        ),
    ]
