# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0009_auto_20161227_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectile',
            name='shot_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_blimp.Player'),
            preserve_default=False,
        ),
    ]
