# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blimp', '0010_projectile_shot_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectile',
            name='shot_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectiles_shot', to='api_blimp.Player'),
        ),
    ]
